-- MySQL Script generated by MySQL Workbench
-- 11/03/16 16:16:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_phelipe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_phelipe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_phelipe` DEFAULT CHARACTER SET utf8 ;
USE `db_phelipe` ;

-- -----------------------------------------------------
-- Table `db_phelipe`.`noticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_phelipe`.`noticia` (
  `id_noticias` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `titulo` VARCHAR(85) NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `img` VARCHAR(85) NOT NULL,
  PRIMARY KEY (`id_noticias`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `db_phelipe`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_phelipe`.`contato` (
  `id_contato` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(85) NOT NULL,
  `email` VARCHAR(85) NOT NULL,
  `assunto` VARCHAR(85) NOT NULL,
  `mensagem` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id_contato`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `db_phelipe`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_phelipe`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(85) NOT NULL,
  `url` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `db_phelipe`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_phelipe`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(85) NOT NULL,
  `email` VARCHAR(85) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
